version: '3'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB : postgres
    volumes:
      - chatops-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    #TODO : healthcheck
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  application:
    image: s3test:1.0.0
    restart: unless-stopped
    networks:
      - app-network
    environment:
      SERVER_PORT: :8080
      DB_CONNECTION_STRING: user=postgres password=postgres dbname=postgres host=localhost port=5432 sslmode=disable
      MINIO_HOST: minio:9000
      MINIO_USER: root
      MINIO_ACCESS_KEY: password
    depends_on:
      - db
      - minio
networks:
  app-network:
    driver: bridge


volumes:
  minio:
    driver: local
  chatops-data: